%Função que imprime o cubo aramado
function imprime3d(faceA, faceB, faceC,faceD,faceE,faceF)

figure,plot3(faceA.x,faceA.y,faceA.z,'r',...
             faceB.x,faceB.y,faceB.z,'g',...
             faceC.x,faceC.y,faceC.z,'b',...
             faceD.x,faceD.y,faceD.z,'c',...
             faceE.x,faceE.y,faceE.z,'m',...
             faceF.x,faceF.y,faceF.z,'y'),...
             grid on, xlabel('X'),ylabel('Y'),zlabel('Z');%,axis([-3 3 -3 3 -3 3]);
end